from lib_openmolar.common.db_orm import om_views

from lib_openmolar.admin.db_orm import (
    admin_avatars,
    admin_patient,
    admin_teeth_present,
    admin_static_fills,
    admin_static_crowns,
    admin_static_roots,
    admin_static_supernumerary,
    admin_static_comments,
    admin_address,
    admin_address_link,
    admin_practices,
    admin_practitioners,
    admin_telephone,
    admin_telephone_link,
    admin_notes_clinical,
    admin_notes_clerical,
    admin_memo_clinical,
    admin_memo_clerical,
    admin_treatments,
    admin_treatment_teeth,
    admin_treatment_fills,
    admin_treatment_crowns,
    admin_treatment_chart,
    admin_users,
    admin_calendar,
    admin_diary_patients,
    admin_perio_recession,
    admin_perio_pocketing,
    admin_perio_plaque,
    admin_perio_bleeding,
    admin_perio_bpe,
    admin_contracted_practitioner,
    admin_invoice_status,
    admin_invoices,
    admin_fees,
    )


## list the modules here also... NOTE the order is important!!
ADMIN_MODULES = (   admin_avatars,
                    admin_users,
                    admin_patient,
                    admin_teeth_present,
                    admin_static_fills,
                    admin_static_crowns,
                    admin_static_roots,
                    admin_static_comments,
                    admin_static_supernumerary,
                    admin_telephone,
                    admin_telephone_link,
                    admin_address,
                    admin_address_link,
                    admin_practices,
                    admin_practitioners,
                    admin_notes_clinical,
                    admin_notes_clerical,
                    admin_memo_clinical,
                    admin_memo_clerical,
                    admin_treatments,
                    admin_treatment_teeth,
                    admin_treatment_fills,
                    admin_treatment_crowns,
                    admin_treatment_chart,
                    admin_calendar,
                    admin_diary_patients,
                    admin_perio_recession,
                    admin_perio_pocketing,
                    admin_perio_plaque,
                    admin_perio_bleeding,
                    admin_perio_bpe,
                    admin_contracted_practitioner,
                    admin_invoice_status,
                    admin_invoices,
                    admin_fees,
                    )
