from add_notes_widget import AddNotesWidget
from notes_widget import NotesWidget
from bpe_widget import BPEWidget
from control_panel import ControlPanel
from details_browser import DetailsBrowser
from patient_interface_options_widget import ChartOptionsWidget, PatientInterfaceOptionsWidget
from statusbar_widget import StatusBarWidget
from summary_line_edit import SummaryLineEdit
from treatment_tree_model import TreatmentTreeModel
from soundex_line_edit import SoundexLineEdit

#subpackages
from chart_editor import *
from chart_widgets import *
