#! /bin/sh

#DEBHELPER#

ln -sf "/etc/openmolar/connections230-available/localhost.conf" "/etc/openmolar/admin/connections230/localhost"
ln -sf "/etc/openmolar/connections-available/demo.conf" "/etc/openmolar/admin/connections/demo"
