#! /bin/sh

# marker to allo debhelper to put stuff here.
#DEBHELPER#

# I have to force removal of these files as they are not
# installed with the deb packaging, but on first run.
# oh, and /etc/openmolar/server.conf is an obsolete location

if [ "$1" = "purge" ]; then
   rm -f "/etc/openmolar/server.conf" || true
   rm -rf "/etc/openmolar/server"  || true
   rm -f "/etc/openmolar/manager_password.txt"  || true
fi

